CREATE TABLE IF NOT EXISTS users (
  id BIGSERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS profiles (
  user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  household_size INTEGER NOT NULL DEFAULT 1,
  location TEXT,
  units TEXT NOT NULL DEFAULT 'litres',
  reduced_motion BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE TABLE IF NOT EXISTS analyses (
  id BIGSERIAL PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  input_data TEXT NOT NULL,
  daily_total DOUBLE PRECISION NOT NULL,
  monthly_total DOUBLE PRECISION NOT NULL,
  breakdown TEXT NOT NULL,
  score INTEGER NOT NULL,
  potential_reduction DOUBLE PRECISION NOT NULL,
  largest_area TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS analysis_recommendations (
  id BIGSERIAL PRIMARY KEY,
  analysis_id BIGINT NOT NULL REFERENCES analyses(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  reason TEXT NOT NULL,
  action TEXT NOT NULL,
  category TEXT NOT NULL,
  priority TEXT NOT NULL,
  impact TEXT NOT NULL
);